packages:
  - 'eslint-config-custom/**'
  - 'nostr/**'
  - 'tailwind-config/**'
  - 'tsconfig/**'
  - 'ui-common/**'
  - 'ui-mobile/**'
  - 'ui-web/**'
  - 'utils/**'
  - 'ndk/ndk'
  - 'ndk/ndk-cache-redis'
  - 'ndk/ndk-cache-dexie'
  - 'ndk/ndk-svelte'
  - 'ndk/ndk-svelte-components'
  - 'ndk/packages/*'
  - 'lib-svelte-kit/**'
